// <auto-generated />
using System;
using Backend_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501155905_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend_API.Models.DeviceBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BoundAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HwidHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentUserId")
                        .IsUnique();

                    b.ToTable("DeviceBindings");
                });

            modelBuilder.Entity("Backend_API.Models.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instructions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LabId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProctorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("LabId");

                    b.HasIndex("ProctorUserId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Backend_API.Models.ExamAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentUserId");

                    b.HasIndex("WorkstationId");

                    b.HasIndex("ExamId", "StudentUserId")
                        .IsUnique();

                    b.ToTable("ExamAssignments");
                });

            modelBuilder.Entity("Backend_API.Models.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentUserId");

                    b.HasIndex("ExamId", "StudentUserId", "Status");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("Backend_API.Models.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowTeacherResetBinding")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedIpRanges")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnforceSingleDeviceBinding")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("Backend_API.Models.Lab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RegisteredTerminals")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("Backend_API.Models.MonitoringEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("ExamSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExamSessionId");

                    b.HasIndex("StudentUserId", "CreatedAtUtc");

                    b.ToTable("MonitoringEvents");
                });

            modelBuilder.Entity("Backend_API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "Email")
                        .IsUnique();

                    b.HasIndex("InstitutionId", "Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend_API.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenJti")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Backend_API.Models.Workstation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LabId", "Name")
                        .IsUnique();

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("Backend_API.Models.DeviceBinding", b =>
                {
                    b.HasOne("Backend_API.Models.User", "StudentUser")
                        .WithMany("DeviceBindings")
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("Backend_API.Models.Exam", b =>
                {
                    b.HasOne("Backend_API.Models.Institution", "Institution")
                        .WithMany("Exams")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.Lab", "Lab")
                        .WithMany("Exams")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend_API.Models.User", "ProctorUser")
                        .WithMany("ProctoredExams")
                        .HasForeignKey("ProctorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Institution");

                    b.Navigation("Lab");

                    b.Navigation("ProctorUser");
                });

            modelBuilder.Entity("Backend_API.Models.ExamAssignment", b =>
                {
                    b.HasOne("Backend_API.Models.Exam", "Exam")
                        .WithMany("Assignments")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.User", "StudentUser")
                        .WithMany("ExamAssignments")
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.Workstation", "Workstation")
                        .WithMany("ExamAssignments")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Exam");

                    b.Navigation("StudentUser");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Backend_API.Models.ExamSession", b =>
                {
                    b.HasOne("Backend_API.Models.Exam", "Exam")
                        .WithMany("Sessions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.User", "StudentUser")
                        .WithMany("ExamSessions")
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("Backend_API.Models.Lab", b =>
                {
                    b.HasOne("Backend_API.Models.Institution", "Institution")
                        .WithMany("Labs")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Backend_API.Models.MonitoringEvent", b =>
                {
                    b.HasOne("Backend_API.Models.ExamSession", "ExamSession")
                        .WithMany("MonitoringEvents")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend_API.Models.User", "StudentUser")
                        .WithMany("MonitoringEvents")
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("Backend_API.Models.User", b =>
                {
                    b.HasOne("Backend_API.Models.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Backend_API.Models.UserSession", b =>
                {
                    b.HasOne("Backend_API.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_API.Models.Workstation", b =>
                {
                    b.HasOne("Backend_API.Models.Lab", "Lab")
                        .WithMany("Workstations")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("Backend_API.Models.Exam", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Backend_API.Models.ExamSession", b =>
                {
                    b.Navigation("MonitoringEvents");
                });

            modelBuilder.Entity("Backend_API.Models.Institution", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Labs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend_API.Models.Lab", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("Backend_API.Models.User", b =>
                {
                    b.Navigation("DeviceBindings");

                    b.Navigation("ExamAssignments");

                    b.Navigation("ExamSessions");

                    b.Navigation("MonitoringEvents");

                    b.Navigation("ProctoredExams");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Backend_API.Models.Workstation", b =>
                {
                    b.Navigation("ExamAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
