// <auto-generated />
using System;
using Backend_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend_API.Models.AiGradingResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SuggestedMarks")
                        .HasColumnType("double precision");

                    b.HasKey("ResultId");

                    b.HasIndex("AnswerId")
                        .IsUnique();

                    b.ToTable("AiGradingResults");
                });

            modelBuilder.Entity("Backend_API.Models.Answer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExamSessionSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AnswerId");

                    b.HasIndex("ExamSessionSessionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Backend_API.Models.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.HasIndex("ActorId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Backend_API.Models.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentDeptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CourseId");

                    b.HasIndex("DepartmentDeptId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Backend_API.Models.Department", b =>
                {
                    b.Property<Guid>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Backend_API.Models.DeviceBinding", b =>
                {
                    b.Property<Guid>("BindingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HwidHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("BindingId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DeviceBindings");
                });

            modelBuilder.Entity("Backend_API.Models.Exam", b =>
                {
                    b.Property<Guid>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AiEvaluationEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedApps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PlagiarismThreshold")
                        .HasColumnType("integer");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExamId");

                    b.HasIndex("SectionId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Backend_API.Models.ExamAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EligibilityNote")
                        .HasColumnType("text");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uuid");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("ExamAssignments");
                });

            modelBuilder.Entity("Backend_API.Models.ExamSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("Backend_API.Models.Lab", b =>
                {
                    b.Property<Guid>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LabId");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("Backend_API.Models.MonitoringEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.HasIndex("ExamSessionId");

                    b.ToTable("MonitoringEvents");
                });

            modelBuilder.Entity("Backend_API.Models.PlagiarismResult", b =>
                {
                    b.Property<Guid>("PlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchingSegments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserIdA")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIdB")
                        .HasColumnType("uuid");

                    b.HasKey("PlagId");

                    b.HasIndex("ExamId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserIdA");

                    b.HasIndex("UserIdB");

                    b.ToTable("PlagiarismResults");
                });

            modelBuilder.Entity("Backend_API.Models.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedOutput")
                        .HasColumnType("text");

                    b.Property<int>("Marks")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Backend_API.Models.Section", b =>
                {
                    b.Property<Guid>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("SectionId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Backend_API.Models.SectionEnrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("SectionId");

                    b.HasIndex("UserId");

                    b.ToTable("SectionEnrollments");
                });

            modelBuilder.Entity("Backend_API.Models.TeacherGradeOverride", b =>
                {
                    b.Property<Guid>("OverrideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<double>("FinalMarks")
                        .HasColumnType("double precision");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("OverriddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("OverrideId");

                    b.HasIndex("AnswerId")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherGradeOverrides");
                });

            modelBuilder.Entity("Backend_API.Models.TestCase", b =>
                {
                    b.Property<Guid>("TestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("TestCaseId");

                    b.HasIndex("QuestionId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("Backend_API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend_API.Models.UserSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Backend_API.Models.Workstation", b =>
                {
                    b.Property<Guid>("WorkstationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uuid");

                    b.Property<string>("MachineNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkstationId");

                    b.HasIndex("LabId");

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("Backend_API.Models.AiGradingResult", b =>
                {
                    b.HasOne("Backend_API.Models.Answer", "Answer")
                        .WithOne("AiGradingResult")
                        .HasForeignKey("Backend_API.Models.AiGradingResult", "AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");
                });

            modelBuilder.Entity("Backend_API.Models.Answer", b =>
                {
                    b.HasOne("Backend_API.Models.ExamSession", "ExamSession")
                        .WithMany("Answers")
                        .HasForeignKey("ExamSessionSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Backend_API.Models.AuditLog", b =>
                {
                    b.HasOne("Backend_API.Models.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Backend_API.Models.Course", b =>
                {
                    b.HasOne("Backend_API.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentDeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Backend_API.Models.DeviceBinding", b =>
                {
                    b.HasOne("Backend_API.Models.User", "User")
                        .WithOne("DeviceBinding")
                        .HasForeignKey("Backend_API.Models.DeviceBinding", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_API.Models.Exam", b =>
                {
                    b.HasOne("Backend_API.Models.Section", "Section")
                        .WithMany("Exams")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Backend_API.Models.ExamAssignment", b =>
                {
                    b.HasOne("Backend_API.Models.Exam", "Exam")
                        .WithMany("Assignments")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.User", "Student")
                        .WithMany("ExamAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.Workstation", "Workstation")
                        .WithMany("ExamAssignments")
                        .HasForeignKey("WorkstationId");

                    b.Navigation("Exam");

                    b.Navigation("Student");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Backend_API.Models.ExamSession", b =>
                {
                    b.HasOne("Backend_API.Models.Exam", "Exam")
                        .WithMany("Sessions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.User", "Student")
                        .WithMany("ExamSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend_API.Models.MonitoringEvent", b =>
                {
                    b.HasOne("Backend_API.Models.ExamSession", "ExamSession")
                        .WithMany("MonitoringEvents")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("Backend_API.Models.PlagiarismResult", b =>
                {
                    b.HasOne("Backend_API.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.User", "StudentA")
                        .WithMany()
                        .HasForeignKey("UserIdA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.User", "StudentB")
                        .WithMany()
                        .HasForeignKey("UserIdB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");

                    b.Navigation("StudentA");

                    b.Navigation("StudentB");
                });

            modelBuilder.Entity("Backend_API.Models.Question", b =>
                {
                    b.HasOne("Backend_API.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Backend_API.Models.Section", b =>
                {
                    b.HasOne("Backend_API.Models.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Backend_API.Models.SectionEnrollment", b =>
                {
                    b.HasOne("Backend_API.Models.Section", "Section")
                        .WithMany("Enrollments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend_API.Models.TeacherGradeOverride", b =>
                {
                    b.HasOne("Backend_API.Models.Answer", "Answer")
                        .WithOne("TeacherGradeOverride")
                        .HasForeignKey("Backend_API.Models.TeacherGradeOverride", "AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_API.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Backend_API.Models.TestCase", b =>
                {
                    b.HasOne("Backend_API.Models.Question", "Question")
                        .WithMany("TestCases")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Backend_API.Models.UserSession", b =>
                {
                    b.HasOne("Backend_API.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_API.Models.Workstation", b =>
                {
                    b.HasOne("Backend_API.Models.Lab", "Lab")
                        .WithMany("Workstations")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("Backend_API.Models.Answer", b =>
                {
                    b.Navigation("AiGradingResult");

                    b.Navigation("TeacherGradeOverride");
                });

            modelBuilder.Entity("Backend_API.Models.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Backend_API.Models.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Backend_API.Models.Exam", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Questions");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Backend_API.Models.ExamSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("MonitoringEvents");
                });

            modelBuilder.Entity("Backend_API.Models.Lab", b =>
                {
                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("Backend_API.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("Backend_API.Models.Section", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Backend_API.Models.User", b =>
                {
                    b.Navigation("DeviceBinding");

                    b.Navigation("ExamAssignments");

                    b.Navigation("ExamSessions");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Backend_API.Models.Workstation", b =>
                {
                    b.Navigation("ExamAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
